inherit_gem:
  rubocop-rails-omakase: rubocop.yml

Style/EndlessMethod:
  Enabled: true
  EnforcedStyle: disallow

Style/SingleLineMethods:
  Enabled: true
  AllowIfMethodIsEmpty: false

Style/SymbolArray:
  Enabled: true
  EnforcedStyle: percent

Bundler/OrderedGems:
  Enabled: true

Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: true

Layout/ExtraSpacing:
  AllowForAlignment: false

Layout/DefEndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: start_of_line

Layout/IndentationWidth:
  Enabled: true

Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: normal

Kode/NoArgumentAlignment:
  Description: "Use exactly one space after commas between method call arguments, preventing column alignment."
  Enabled: true
  VersionAdded: "0.1"

Kode/NoHashAlignment:
  Description: "Use exactly one space after `=>` or `:` in hash pairs, preventing column alignment."
  Enabled: true
  VersionAdded: "0.1"

Kode/NoAssignmentAlignment:
  Description: "Use exactly one space before `=` in local/instance variable and setter assignments, preventing column alignment."
  Enabled: true
  VersionAdded: "0.1"
